theme: jekyll-theme-midnight
title: Data Incubator Project
description: Ali Azad <br> Data Enthusiast <br> ali.azad -at- gatech.edu
show_downloads: false
google_analytics:   #[Your Google Analytics tracking ID]
